config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:new, :create, :destroy]
  resources :comments
  resources :ratings
  resources :students, only: [:new, :create, :show, :destroy,:analytics, :update, :edit]
  resources :teachers
  root to: 'teachers#show'
  get "/signup", to: "teachers#new", as: "signup"
  get "/login", to: "sessions#new"
  get '/signin', to: 'sessions#new'
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get '/analytics', to: 'students#analytics', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
  has_many :likes
  has_many :liking_teachers, through: :likes, source: :teacher

  def self.comment_count
      self.all.count
  end

  def like_count
    self.likes.count
  end

  def liking_teacher_names
    #returns array of the teachers names who liked the comment
    self.liking_teachers.collect do |teacher|
      teacher.username
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
   @comment = Comment.new
   #@teachers = Teacher.all
   @teacher = current_teacher
   @students = Student.all
  end

  def show
   @comment = Comment.find(params[:id])
  end

  def create
   @comment = Comment.new(comment_params)
   if @comment.valid?
     @comment.save
     redirect_to new_rating_path
   else
    flash[:error] = @comment.errors.full_messages
    redirect_to new_comment_path
   end
  end

  def edit
    @comment = Comment.find(params[:id])
    #@teachers = Teacher.all
    @teacher = current_teacher
    @students = Student.all
  end

  def update
    @comment = Comment.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to @comment
    else
     flash[:error] = @comment.errors.full_messages
     redirect_to edit_comment_path
    end
   end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end


  private

  def comment_params
    params.require(:comment).permit(:content, :student_id, :teacher_id)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<ul>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <li><%= error %> </li>
  <% end %>
  <% end %>

</ul>

<%= form_for @comment do |f| %>
<%= f.label :content, "End of Year Comment:" %>
<%= f.text_field :content %>


<%= f.hidden_field :teacher_id, :value => @teacher.id %>
<%= f.collection_select :student_id, @students, :id, :name %>


<%= f.submit %>

<% end %>

app/views/comments/index.html.erb
<h3>Total Comments: <%= Comment.comment_count %></h3>
<ul>
  <% @comments.all.each do |comment| %>
   <li>Teacher: <%= comment.teacher.username %> | Student: <%= link_to comment.student.name, comment.student %> | Comment: <%= link_to comment.content, comment %> | Likes: <%= comment.like_count %> </li>
  <% end %>
</ul>

<%= link_to new_comment_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Add Another Comment
<% end %>

app/views/comments/new.html.erb
<ul>
  <% if flash[:error] %>
  <% flash[:error].each do |error| %>
  <li><%= error %> </li>
  <% end %>
  <% end %>

</ul>

<%= form_for @comment do |f| %>
<%= f.label :content %>
<%= f.text_field :content %>


<%= f.collection_select :teacher_id, @teachers, :id, :username %>
<%= f.collection_select :student_id, @students, :id, :name %>

<%= f.submit %>

<% end %>

app/views/comments/show.html.erb
<h2>Comment for: <%= link_to @comment.student.name, @comment.student %> | From : <%= @comment.teacher.username %></h2><br>

<h4>Comment: <%= @comment.content %></h4><br>

<%= link_to 'Edit Comment', edit_comment_path(@comment), class: 'btn btn-warning'  %>
<%= link_to 'Delete Comment', comment_path(@comment), method: :delete, class: 'btn btn-danger'  %>

<%= link_to new_comment_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Add Another Comment
<% end %>

<%= link_to new_rating_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Rating
<% end %>

<%= form_tag("/likes", method: "post", class:"btn btn-info") do %>
<i class="glyphicon glyphicon-thumbs-up"></i>
<!--  posts to likes#create-->
<%= hidden_field_tag 'like[teacher_id]' , session[:teacher_id]%>
<%= hidden_field_tag 'like[comment_id]' , params[:id]%>
<%= submit_tag("Like")%>
<% end %>
<p>Comment has <%= @comment.like_count %> likes.</p>
<label> People who have liked this</label>
<ol>
  <% @comment.liking_teacher_names.each do |name|%>
  <li><%= name %></li>
  <% end %>
</ol>