config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:new, :create, :destroy]
  resources :comments
  resources :ratings
  resources :students, only: [:new, :create, :show, :destroy,:analytics, :update, :edit]
  resources :teachers
  root to: 'teachers#show'
  get "/signup", to: "teachers#new", as: "signup"
  get "/login", to: "sessions#new"
  get '/signin', to: 'sessions#new'
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get '/analytics', to: 'students#analytics', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :student, dependent: :destroy
  validates :gpa, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
  validates :discipline, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :grit, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}

def self.most_popular_learning_style
  Rating.group(:learning_style).count.sort_by{|_key, v| v}.last[0]
end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = Rating.all
  end

  def new
    @rating = Rating.new
    @students = Student.all
  end

  def create
    @rating = Rating.new(rating_params)
    #byebug
    if @rating.save
      redirect_to rating_path(@rating)
    else
      flash[:error] = @rating.errors.full_messages
      redirect_to new_rating_path
    end
  end

  def show
    @rating = Rating.find(params[:id])
    @student = @rating.student
  end


  def edit
    @rating = Rating.find(params[:id])
  end

  def update
    @rating = Rating.find(params[:id])
    if @rating.update(rating_params)
      redirect_to rating_path(@rating)
    else
      flash[:error] = @rating.errors.full_messages
      redirect_to edit_rating_path(@rating)
    end
  end

  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to teacher_path(current_teacher)
  end


  private

  def rating_params
    params.require(:rating).permit(:discipline, :learning_style, :grit, :gpa, :subject, :student_id, :author)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<div class='container'>
<% if flash[:error] %>
<label>Form could not be submitted due to: </label>
  <% flash[:error].each do |err|%>
    <li><%= err %></li>
  <% end %>
<% end %>
<h3>Year End Report</h3><br>
<%= form_for @rating do |f| %>
<%= f.label :discipline, "Behavior" %><br>
<%= f.number_field :discipline, placeholder: " Rate from 1-10" %><br>

<%= f.label :learning_style, "Learning Style:" %><br>
<%= f.text_field :learning_style, placeholder: "Learning Style" %><br>

<%= f.label :grit, "Effort" %><br>
<%= f.number_field :grit, placeholder: "Rate from 1-10" %><br>

<%= f.label :subject, "Subject" %><br>
<%= f.text_field :subject, placeholder: "Subject" %><br>

<%= f.label :gpa, "Final Grade" %><br>
<%= f.number_field :gpa, class: :text_field, step: 0.1, placeholder: "Rate from 1-5" %><br>

<%= f.label :subject, "Author" %><br>
<%= f.text_field :author, placeholder: "Author", value: current_teacher_name %><br>


<br><%= f.label :student, "Select a Student" %><br>
<%= f.collection_select :student_id, @students, :id, :name %><br>

<%= f.submit %>
<% end %>
</div>

app/views/ratings/index.html.erb
<ul>
  <% @ratings.each do |rating| %>
    <li><%= rating.student.name %></li>
  <% end %>
</ul>

app/views/ratings/show.html.erb
<h2>Progress Report For: <%=link_to @student.name, student_path(@student) %></h2><br>

<h3>From: <%=@rating.author %> </h3><br>
<h4>
  Behavior: <%= @rating.discipline %><br>
    Learning Style: <%= @rating.learning_style %><br>
     Effort: <%= @rating.grit %><br>
     Subject: <%= @rating.subject %><br>
      Final Grade: <%= @rating.gpa %><br>
        </h4>

        <%= link_to new_student_path, class: 'btn btn-success' do %>
          <i class="glyphicon glyphicon-plus"></i> Create Another Student
        <% end %>

        <%= link_to new_comment_path, class: 'btn btn-success' do %>
          <i class="glyphicon glyphicon-plus"></i> Create Another Comment
        <% end %>
<%= link_to 'Delete Rating', rating_path(@rating), method: :delete, class: 'btn btn-danger'  %>