config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:new, :create, :destroy]
  resources :comments
  resources :ratings
  resources :students, only: [:new, :create, :show, :destroy,:analytics, :update, :edit]
  resources :teachers
  root to: 'teachers#show'
  get "/signup", to: "teachers#new", as: "signup"
  get "/login", to: "sessions#new"
  get '/signin', to: 'sessions#new'
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get '/analytics', to: 'students#analytics', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :students, through: :comments, dependent: :destroy
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :likes
  has_many :liked_comments, through: :likes, source: :comments

  def student_count
    "You currently have #{self.students.count} student(s)."
  end

  def comment_count
    "You have currently commented #{self.comments.count} times."
  end

  def student_of_the_day
    self.students.all.sample.name
  end

  def teacher_likes_count
    self.likes.count
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def show
    if logged_in?
      flash[:msg] = "Welcome #{current_teacher.username}"
    else
    end
    @teacher = Teacher.find(session[:teacher_id])
    if @teacher.students.count > 0
    @random_student = current_teacher.student_of_the_day
    @comment_count = current_teacher.comment_count
  end

  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.valid?
      @teacher.save
      session[:teacher_id] = @teacher.id
      redirect_to teacher_path(@teacher)
    else
      flash[:error] = @teacher.errors.full_messages
      redirect_to new_teacher_path
    end
  end

  private

  def set_teacher
   @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:username, :password)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/index.html.erb
<h1>home page</h1>
<ul>
  <% @teachers.each do |t| %>
  <li><%= t.username %></li>
  <% end %>
</ul>

app/views/teachers/new.html.erb
<%= form_for @teacher do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.submit %>
<% end %>

app/views/teachers/show.html.erb
<h2>Welcome, <%= @teacher.username %>. <%= @teacher.student_count %></h2>
<h3><%= @comment_count %></h3>
<h3>You have given: <%= @teacher.teacher_likes_count %> likes </h3>
<h4>Your students are:</h4>

<ul>
  <% @teacher.students.each do |student| %>
    <li><%= link_to student.name, student %></li>
  <% end %>
</ul>

<%if current_teacher.students.count > 0 %>
<h4>Don't forget to give some extra praise to <%= @random_student %> today. </h4>
<% end %>


<%= link_to new_student_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Create New Student
<% end %>

<%= link_to new_comment_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Comment for Existing Student
<% end %>

<%= link_to new_rating_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Create Rating for Existing Student
<% end %>