config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:new, :create, :destroy]
  resources :comments
  resources :ratings
  resources :students, only: [:new, :create, :show, :destroy,:analytics, :update, :edit]
  resources :teachers
  root to: 'teachers#show'
  get "/signup", to: "teachers#new", as: "signup"
  get "/login", to: "sessions#new"
  get '/signin', to: 'sessions#new'
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get '/analytics', to: 'students#analytics', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyStudents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
          <h4>Menu</h4>

          <p><%= link_to 'Profile', root_path %></p>
          <p><%= link_to 'Create a New Student', new_student_path%></p>
          <p><%= link_to 'Teacher Talk', comments_path%></p>
          <p><%= link_to 'School Rankings', analytics_path%></p>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>